### ISSUE TITLE
Improper screen orientation in landscape mode on mobile devices

### ISSUE THREAD

**Issue by mihiraggarwal** [rachittt/me#5]
![Website in landscape mode](https://user-images.githubusercontent.com/49950982/66415883-3faf1980-ea1a-11e9-971b-32c62d722d4a.jpeg)
The background image is not fully visible. It is divided horizontally to accomodate the screen size acccordingly and lacks responsiveness.

**Comment by rachittt** [comment]
Hey, thanks for reporting. We can simply fix the screen orientation in css to solve this. Do you want to do it ? @mihiraggarwal

**Comment by rachittt** [comment]
hey, I am not sure if we can lock the screen orientation in html so I closing the issue for now but if you can somehow make it responsive, do put up a pull request. Thanks for your time though 😀
